"""LLM package initialization."""

from .client import LLMClient
from .prompts import (
    MASTER_AGENT_SYSTEM_PROMPT,
    SALES_AGENT_SYSTEM_PROMPT,
    TECHNICAL_AGENT_SYSTEM_PROMPT,
    PRICING_AGENT_SYSTEM_PROMPT,
)

__all__ = [
    "LLMClient",
    "MASTER_AGENT_SYSTEM_PROMPT",
    "SALES_AGENT_SYSTEM_PROMPT",
    "TECHNICAL_AGENT_SYSTEM_PROMPT",
    "PRICING_AGENT_SYSTEM_PROMPT",
]
